name       : lib2geom
version    : 1.1
release    : 1
source     :
    - https://gitlab.com/inkscape/lib2geom/-/archive/1.1/lib2geom-1.1.tar.gz : 8bc63348ac7cb1343b0500d4b4506e30aaa7477e80ebd7ac89a8c382f4d788c4
license    :
    - LGPL-2.1-only
    - MPL-1.1
component  : programming.library
summary    : Easy to use 2D geometry library in C++
description: |
    Easy to use 2D geometry library in C++
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gsl)
    - double-conversion-devel
    - gtest-devel
    - libboost-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Fix-ABI-creation.patch
    %cmake_ninja -D2GEOM_BUILD_SHARED=yes \
                -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
