name       : lib2geom
version    : '1.3'
release    : 3
source     :
    - https://gitlab.com/inkscape/lib2geom/-/archive/1.3/lib2geom-1.3.tar.bz2 : bd07f2a1322fcad16a55a1901207faa55dffdecebc56a00eabd4575f62e043c9
license    :
    - LGPL-2.1-only
    - MPL-1.1
component  : programming.library
summary    : Easy to use 2D geometry library in C++
description: |
    Easy to use 2D geometry library in C++
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gsl)
    - double-conversion-devel
    - gtest-devel
    - libboost-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Fix-ABI-creation.patch
    %cmake_ninja -D2GEOM_BUILD_SHARED=yes \
                -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
